export enum ScannerStatus {
  IDLE = 'IDLE',
  INITIALIZING = 'INITIALIZING',
  DETECTING = 'DETECTING',
  CAPTURED = 'CAPTURED',
  SCANNING = 'SCANNING',
  SCAN_PASSED = 'SCAN_PASSED',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
  FINALIZING = 'FINALIZING',
  COUNTDOWN = 'COUNTDOWN',
  ONBOARDED = 'ONBOARDED',
  WELCOME = 'WELCOME',
}